# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  dogocraft_config = debug

else ifeq ($(config),release)
  dogocraft_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := dogocraft

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

dogocraft:
ifneq (,$(dogocraft_config))
	@echo "==== Building dogocraft ($(dogocraft_config)) ===="
	@${MAKE} --no-print-directory -C . -f dogocraft.make config=$(dogocraft_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f dogocraft.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   dogocraft"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"